//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class alexiaEntities : DbContext
{
    public alexiaEntities()
        : base("name=alexiaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<alumnes> alumnes { get; set; }
    public virtual DbSet<avaluacions> avaluacions { get; set; }
    public virtual DbSet<avaluar> avaluar { get; set; }
    public virtual DbSet<cicles> cicles { get; set; }
    public virtual DbSet<cursos> cursos { get; set; }
    public virtual DbSet<moduls_prof> moduls_prof { get; set; }
    public virtual DbSet<persones> persones { get; set; }
    public virtual DbSet<professors> professors { get; set; }
    public virtual DbSet<ufs> ufs { get; set; }
}
